/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/base/button.vue')['default']
    Footer: typeof import('./ui/components/footer.vue')['default']
    Header: typeof import('./ui/components/header.vue')['default']
    Input: typeof import('./components/base/input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Transition: typeof import('./ui/components/transition/index.vue')['default']
    Wizard: typeof import('./ui/components/wizard/index.vue')['default']
  }
}
